# Generated by Django 5.1.2 on 2024-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_title_reserve_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
