# Generated by Django 5.1.2 on 2024-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.CharField(choices=[('ROMAN', 'Roman'), ('SCIENCE', 'Science'), ('HISTOIRE', 'Histoire'), ('POLICIER', 'Policier'), ('FANTASY', 'Fantasy'), ('BIOGRAPHIE', 'Biographie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
