# Generated by Django 5.1.2 on 2024-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_reservationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationhistory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Annulée')], max_length=20),
        ),
    ]
